### ISSUE TITLE
PHP 8.1 changes the URL

### ISSUE THREAD

**Issue by maico320** [julienV/Joomla-Tracks#101]
Hi, just noticed a problem with my Joomla 3.10.11 tracks component, latest version.
When running on PHP 7.4 the url to the round results is normal  **/index.php/menu-link/my-project-name/result-100-UK**
When running on PHP 8.1 the url gets modified to just  **/index/menu-link/result-100-**  even the language string gets omitted and it just gets stuck on the project page when clicked.
Any ideas?

**Comment by julienV** [comment]
Hi, I don't really see why it would come from tracks... does it work as expected for other extensions ?

**Comment by maico320** [comment]
Hi, yes everything else seems to work, only the link to round results is broken for what I can gather...strange.
