### ISSUE TITLE
Joomla 3.2.3

### ISSUE THREAD

**Issue by quentaro81** [julienV/Joomla-Tracks#27]
Joomla 3.2.3

Fatal error: Class BaseController cannot extend from interface JController in /home/granturi/public_html/joomla/administrator/components/com_tracks/controllers/base.php on line 26

Please help me - It would be important for my racing site! - Great extension!

**Comment by JKoelman** [comment]
@julienV  is there any news about this one.

the thing is that i'm considering to update the files but if you have it in the pipeline for a release in a few months then i'll let it slide.

**Comment by julienV** [comment]
i've been working on it, i am too far from being done (maybe not all non-essentials backend features yet though)

**Comment by julienV** [comment]
in fact i ditched fof, and i adapted with redCORE instead (you can find it on github)
I pushed my current branch, you can try it out if you want to see how it looks (you will need to install redCORE too first, use the latest from the repo, 1.4.13).
there are phing build script to help you build install packages.

**Comment by JKoelman** [comment]
> you can try it out if you want to see how it looks

Was wondering how it looked so did give it a try. Downloaded the files, installed redCore + installed the tracks components. Did ran into a few problems with installing (problem with xml) but that could be expected so no problem. Did take take a look around and sorry to say but at the moment i do prefer the way it looks with the version i'm currently having.  It can be that in a later stadium the opinion is different but for now it's not.

uhm, if i wanted to post issues with that branche:  do i've to add them here?

**Comment by julienV** [comment]
it's a work in progress, so it'll get better... and it works on both 2.5 and 3.x.
don't post issues just yet, i'm still an early stage.

**Comment by JKoelman** [comment]
> don't post issues just yet, i'm still an early stage.

alright won't do that :smile:.. but good to know that you're busy with it.

**Comment by julienV** [comment]
updated a bit the code today, you can find the release here
https://github.com/julienV/Joomla-Tracks/releases/tag/3.0.alpha.1.0

not all frontend views are functionnal (especially since i didn't implement the project round selector yet...), but most are ;)

modules and plugins not tested, so don't expect miracles.

**Comment by julienV** [comment]
closing this one, as it's ongoing
