### ISSUE TITLE
3.0.a.1.0 - Backend Publish/Unpublish - Undefined $id

### ISSUE THREAD

**Issue by JKoelman** [julienV/Joomla-Tracks#31]
When pressing the publish/Unpublish icon in the views, like Competitions, it will lead to an entry in the log.

```Notice:  Undefined property: TracksTablexxxx::$`id` in C:\wamp\www\0904a\libraries\redcore\table\table.php on line 670```

(Joomla 3.4.x)

**Comment by julienV** [comment]
comes from redcore, already fix in the code base.
