### ISSUE TITLE
3.0.a.1.0 - Backend Competitions view, delete - Exception:Unknown column 'p.competition_id_id' in 'where clause' 

### ISSUE THREAD

**Issue by JKoelman** [julienV/Joomla-Tracks#33]
Tried to remove a competition and got the following message.

```Exception:Unknown column 'p.competition_id_id' in 'where clause' SQL=SELECT p.id FROM j0904a_tracks_projects AS p WHERE p.competition_id_id in (2) ```  beside that it was also showing some debug info and think that's not that nice to show.

**Comment by julienV** [comment]
fixed for next
