### ISSUE TITLE
Can't acces cpanel

### ISSUE THREAD

**Issue by serafinr** [julienV/Joomla-Tracks#35]
I installed tracks 1.0 for J3.x but when I tried to open a project I receive this message. I can't access the control panel of tracks.

I was waiting for the Tracks J3.x for a while, I hope you can fix it and put it ready soon. Thanks

 404 Tracks lib - redCORE init failed

**Comment by julienV** [comment]
take the latest release from here: https://github.com/julienV/Joomla-Tracks/releases
there will be a new one realy soon
