### ISSUE TITLE
Problem Managing Content Element - Cannot add Foreign Key constraint.

### ISSUE THREAD

**Issue by Robbie8** [julienV/Joomla-Tracks#36]
I am running Joomla 3.4.1 and am running the upgrade from Tracks Beta 2.0 to Tracks Beta 3.0 - The attached error message is issued during the installation process which reports that it has completed successfully. No issues have been identified during testing in Beta 3.0
![install content element error](https://cloud.githubusercontent.com/assets/11949925/7146163/732c7376-e2e9-11e4-8600-f75bc259a56c.GIF)

**Comment by julienV** [comment]
don't worry about it, it's a redCORE install bug

**Comment by Robbie8** [comment]
Yes but is it going to be fixed?

**Comment by julienV** [comment]
probably, but it's not an issue for tracks anyway
