### ISSUE TITLE
Back Button - Enhancement to Joomla 3.0 version of Tracks

### ISSUE THREAD

**Issue by Robbie8** [julienV/Joomla-Tracks#37]
In the Events and Results view in the admin screen, could there be a back button (or close button) which would take you to the next level up e.g. from Results to Events page, or events to project Round - at present this is done using the Broker back button, but an application back button would be a better approach?

See the screen print for a suggestion of what is requested
![events and results](https://cloud.githubusercontent.com/assets/11949925/7146270/47a19276-e2ea-11e4-99fc-c80a53b522ad.GIF)

**Comment by julienV** [comment]
i have added the breadcrumbs for that purpose, you can click on the project name just above the buttons. Same if you go to edit results,you can go back one or 2 levels using the breadcrumbs

**Comment by Robbie8** [comment]
OK - I understand - changed the way we do it.
