### ISSUE TITLE
Default start and end times for Rounds - Enhancement Request

### ISSUE THREAD

**Issue by Robbie8** [julienV/Joomla-Tracks#38]
Hi, 
All the rounds we run have a time from 13:00 to 18:00. I was wondering if a default time can be set, that will propagate down to each of the individual Rounds, if no explicit time is set per round/ event. This would save me having to set the same time range in mutiple rounds ?

I was thinking this could possibly be done in the Rounds view, or in the Settings

Thanks

**Comment by julienV** [comment]
you can edit administrator/components/com_tracks/models/forms/projectround.php, and write
default="13:00" to start_date and 18:00 for end_date
https://github.com/julienV/Joomla-Tracks/blob/dev/component/admin/models/forms/projectround.xml#L27

**Comment by Robbie8** [comment]
I have tested this and it works - thanks
