### ISSUE TITLE
Team Ranking doesn't calculate correctly

### ISSUE THREAD

**Issue by tc-ganimed** [julienV/Joomla-Tracks#39]
Hi Julien,

first of all thanks for the new version. It's mostly running well.

I think however there is an Issue in the Team ranking. Here is my Scenario:
Driver can team in pair sharing a car but most are driving individually. Participation of a race earns you 10 points, points on position are very complicated (multiples series in a race) so I use the bonus point feature for that. 

Lets say: 
Adam and Bob drive in a team. Christian is driving alone. 
Race 1: 1st: Christian (10 bonus points) ; 2nd Adam (15 bonus points)
Race 2: 1st: Bob (20 bonus points); 2nd Christian (10 bonus points) ; 

This is what the table says:
Driver Ranking:
1: Christian: 40 (correct)
2: Bob: 30 (correct)
3: Adam: 25 (correct)

Team Ranking:
1: Adam/Bob: 25 (incorrect)
2 Christian: 0 (incorrect)

All drivers are correctly allotted to the teams. All points are saved.

**Comment by tc-ganimed** [comment]
If you look at the full table you see
Adam/Bob best place 2 - so its not considering bob at all
Christian: is all 0 - which is completely strange

**Comment by tc-ganimed** [comment]
The issue is a dublicate to no 18 here on Github or http://tracks.jlv-solutions.com/forum/viewtopic.php?f=12&t=5066 in the forum. 
The specified workaround 2 does work for me.

**Comment by julienV** [comment]
fixed for next
