### ISSUE TITLE
Team vehicle image upload: select button floating away

### ISSUE THREAD

**Issue by tc-ganimed** [julienV/Joomla-Tracks#40]
Hi,

just a minor:
The Select button in the vehicle screen, in the team view is floating away.

![image](https://cloud.githubusercontent.com/assets/9823942/7392987/91823bbe-ee8b-11e4-9847-00dcb556962f.png)

Screen is from a Chrome 42 (64bit)

**Comment by julienV** [comment]
fixed for next
