### ISSUE TITLE
Can't Save any Record

### ISSUE THREAD

**Issue by quartelg** [julienV/Joomla-Tracks#41]
Hi guys...

I upgraded to tracks 3.0. All the previous records are there, but when i try to add someting new (could be a season, a indivual, whatever), I have this error:

Fatal error: Call to undefined method TracksTableSeason::hasPrimaryKey() in /home/liga1029/public_html/libraries/redcore/table/table.php on line 529

This is a component or my system error?

**Comment by julienV** [comment]
hi, are you on joomla 2.5 or 3.x ?

**Comment by quartelg** [comment]
joomla 2.5

**Comment by julienV** [comment]
looks like a bug with redform, i'll see what i can do

**Comment by julienV** [comment]
should be fixed with 3.0.beta.3.4... better late than never !

**Comment by Robbie8** [comment]
Julien
I tried to install 3.4 on a Joomla 3.4.3 version and it failed - JInstaller: :Install: Can't find XML setup file., Unable to find install package - any advice please?

**Comment by julienV** [comment]
did you unzip first ?

**Comment by sudkarting** [comment]
Bonjour Julien,

J'ai installé la version 3.0.4 sur un Joomla 3.5, toutes les données sont ok par contre plus de possibilité de sauver dans des menus, articles de Joomla et un affichage bizarre...
C'est assez urgent merci.

**Comment by sudkarting** [comment]
Hi
is that version 3.0.4 is compatible Redcore 1.8.0?

Regards

**Comment by julienV** [comment]
sorry, on vacation, coming back tomorrow, but in theory it should be.
