### ISSUE TITLE
Unable to select round result from creating new menu item

### ISSUE THREAD

**Issue by Redline260** [julienV/Joomla-Tracks#42]
Hello Julien,

I have upgraded from Joomla 2.5 to 3.4 and updated my Tracks extension to v3 beta 3. I am trying to create a new menu for a round result and when doing so I am asked as usual to select a project round. Upon doing so my project rounds appear however they are all greyed out and I am unable to select any. Therefore i cannot create a new menu item in joomla using tracks.
Am i doing something wrong? I can take a screenshot to show you. Im a little dumbfounded right now

Mark

**Comment by Redline260** [comment]
Any news on when this will be fixed or how I can fix it?

**Comment by julienV** [comment]
i'll try before end of the week... remind me if not

**Comment by julienV** [comment]
fixed in latest release
