### ISSUE TITLE
Duplicate Project Issue

### ISSUE THREAD

**Issue by Jinobix** [julienV/Joomla-Tracks#43]
In the Joomla 2.5 version of tracks, when I duplicated a project, it copied all the rounds and events.
Now in Tracks 3.0 Beta (Using Joomla 3.4.1) - When a project is duplicated "Save as Copy". It does not copy all the rounds and events over too. Only the project name.

Also, the older tracks had "(copy of)" in the copied project title when duplicated but that's not much of an issue.

I hope this is an easy fix as it saves so much time. Would this be possible?

**Comment by julienV** [comment]
sure, i'll add it asap

**Comment by julienV** [comment]
implemented

**Comment by loloprim** [comment]
probleme egalement lors ajout pilote dans une round ou event (add all) il ajoute 2 fois les meme pilotes
lorsque l'on veut entrer les resultaat idem (add all) ajoute 2 fois le pilote
