### ISSUE TITLE
AUP Suggestion

### ISSUE THREAD

**Issue by Jinobix** [julienV/Joomla-Tracks#48]
Hi there. This is more of a suggestion. Have you heard of Alphauserpoints?
Can Tracks have an AUP plugin? Or just a way to add a new rule into AUP to work with tracks?
We have a website that uses both Tracks & an extension named AlphaUserPoints.
http://www.alphaplug.com/index.php/products/alphauserpoints.html

AUP is basically a way for users to collect/spend points from pretty much anything. We have used AUP with other extensions before. But if users points from tracks can automatically be added to their AlphaUserPoints....That would be amazing.

Let me know what ya think. No matter what the outcome, I just wanna thank you for making an amazing joomla extension.

**Comment by julienV** [comment]
it's probably possible, but i guess it's a bit late to answer ;)
