### ISSUE TITLE
Partecipants ADD ALL 

### ISSUE THREAD

**Issue by sil3ntskull** [julienV/Joomla-Tracks#49]
I have done a clean installation of tracks on joomla 3.2
After adding partecipants to a project, when i add all to an event resuls, it duplicates the drivers so that i have to delete manually. IS it an issue?

Then julien, is it possible to ipmort tracks 2,0 datas in a clean tracks 3 install?
thanks

**Comment by julienV** [comment]
i'll check for the duplication issue. As for the import, i think it should work if first install the latest on your 2.5 version, then on your 3.x. Then replace tracks 3.x tables with the 2.5 tables.
of course, backup before you try this !

**Comment by julienV** [comment]
fixed in 3.0.2
