### ISSUE TITLE
Customized Result tables

### ISSUE THREAD

**Issue by serafinr** [julienV/Joomla-Tracks#50]
Helo Julien.
Thanks for updating this great component!
Do you think it is possible to add a feature on settings that can display the data you want to show to your visitors? I mean, maybe some website wants to display just the rider, team and points, maybe other one wants to display rider's number also, or so... Actually this is a feature (limited to show teams and points) for the modules, not for the component.

Sometimes is no the same team than make, so I don't know if is possible to add this field when capture participants data. Eg. I use this component for Motorcycles competition: One rider rides on a Kawasaki (make) and rides for The Kawasaki Factory Team (team). Some riders participate without a team, but they rides on a brand of motorcycle (make).

Congrats again

**Comment by julienV** [comment]
for fields display, you can use a template override, it's not so hard...
for adding fields, it's a bit more complicated at this point. Maybe i'll add the possibility to use custom fields at some poitn, but really don't have the time for this atm
