### ISSUE TITLE
Adding results.

### ISSUE THREAD

**Issue by chrisbana** [julienV/Joomla-Tracks#51]
Hi,

I am using a clean install of joomla v3.4.5 and have installed the latest version of tracks 3. that i installed today.
I did have an issue with redcore conflicting with adding menu items but installing the latest redcore version has fixed that, thank you.

However, i don't seem to be able to add results and i am not sure if it is something i am doing wrong or a problem with tracks.
I have added a project, season, competion, round and event type (i assume the "event" type is the old "sub round" from the old version. )
i can add participants to the round but i am unable to see how to add the results?
I currently use an old version of tracks on another site for a poker league which works fine.

**Comment by julienV** [comment]
Well, you should have input boxes in front of every participant in the event results screen. see screenshot
![jl3x - administration - chromium_001](https://cloud.githubusercontent.com/assets/169588/10884849/884fe6fe-817a-11e5-9aec-465a93204531.jpg)

**Comment by chrisbana** [comment]
I reinstalled it and it is all fine now thank you


Sent by Outlook for Android





On Mon, Nov 2, 2015 at 6:58 AM -0800, "Julien Vonthron" <notifications@github.com> wrote:
Well, you should have input boxes in front of every participant in the event results screen. see screenshot
![jl3x - administration - chromium_001](https://cloud.githubusercontent.com/assets/169588/10884849/884fe6fe-817a-11e5-9aec-465a93204531.jpg)


---
