### ISSUE TITLE
redCore Versions at Joomla 3.5.1

### ISSUE THREAD

**Issue by Frog65** [julienV/Joomla-Tracks#52]
hi
after i updated my joomla from 3.4.8 to 3.5.1 i get problems by open some forms (individuals, projects, tracks-event-types...)
i was happy when i saw that you already work on a solution. :-)
now i installed the tracks 3.0.1 with redCore 1.8.3

I checked tracks and now it seems everything works again!!! 
BUT...

i´m just wondering about **the error after install** and **the viewed version-numbers of installed redCore components**. why not all components of redCore are version 1.8.3???
Can this make problems?

can you have a look and give me a short feedback if everything OK?
_errormessage after install tracks:_
http://abload.de/img/redcore_1_8_3_error_33szzu.jpg
(http://www.directupload.net/file/d/4325/onrtnshf_jpg.htm)
i_nstalled redCore versions:_
http://abload.de/img/redcore_1_8_3_error_4hdz9q.jpg
(http://www.directupload.net/file/d/4325/g67o4gy8_jpg.htm)

thanks allot
Frog

**Comment by julienV** [comment]
don't worry about the install warning.
however, the redCORE extensions should indeed show a different version number (1.8.0 for most, 1.8.3 for component).
maybe try to install again.
you can download standalone redCORE here too: https://github.com/redCOMPONENT-COM/redCORE/releases

**Comment by Frog65** [comment]
hi julien,
when i installed the redCore 1.8.2 standalone the same error message will be appear...

http://abload.de/img/redcore_1_8_2_error_1dtkwz.jpg
http://abload.de/img/redcore_1_8_2_error_2d0k8i.jpg

i cant uninstall redCore because tracks used them...

can i update component for component seperatly?

thx Frog

**Comment by julienV** [comment]
Maybe rather open an issue on redCORE repository, people in charge of it will be more helpfull
https://github.com/redCOMPONENT-COM/redCORE/issues

**Comment by Frog65** [comment]
i will do that. Thanks for your time...
