### ISSUE TITLE
sports multi championship is possible ?

### ISSUE THREAD

**Issue by Fotoraduno** [julienV/Joomla-Tracks#53]
Is possible a sport multi championship ?
My problem is in the gestion of individuals. 
For example....
I have a 1 sport  moto race. 
in to moto race is present 3 championship.
1)moto race ireland 
2)moto race japan 
3) moto race africa
in each championship it's present "season" ( 2016), "round"(march, april...ecc..) "event type" (125cc,250cc..ecc...).
The problem is in to individual,  for each championships the idividual it's different.
I have create  1 project for 1 championship ( example.. project moto japan, project moto irelan...ecc)
i have a partecipant different for each championship,
can be divided the individuals to championship or enter a field in individuals to quickly recognize them?
I have many different participants.
or I have to put together all individuals and select the participants for each project ?
any championship is managed by a different user
it would be nice if every project participants and team are unique.

**Comment by julienV** [comment]
teams and individuals are global to the extension, when you add them to projects, they become participants.
If you are asking if individuals and teams can be defined only in projects, the answer is no...
