### ISSUE TITLE
Tracks not showing in my template.

### ISSUE THREAD

**Issue by gutocolvara** [julienV/Joomla-Tracks#54]
i´ve tried everything, i have a JA teline V template with T3 framework and bootstraps, every other component work´s fine, but tracks does not load at all! i get a blank (no content page).

my page is www.clubes.miniz.com.br

the only way to work is putting the track project list using a standard (protostar) layout for this page, and using another menu item with a iframe on it in order to show. See "Tracks" and "tracks 1" buttons on topnav.

i have no clue in how to fix that.

**Comment by julienV** [comment]
can't really say... try without seo maybe ?
or send me an access at jlv@jlv-solutions.com

**Comment by gutocolvara** [comment]
Sorry,  dont know what SEO is, and how to disable it.

**Comment by gutocolvara** [comment]
Ok, got it,..change a lot of SEO options, but no good...with some configs i got 500 error page. 

i will send you access right now.

**Comment by julienV** [comment]
was an issue of the template
