### ISSUE TITLE
wrong sort on frontend

### ISSUE THREAD

**Issue by Frog65** [julienV/Joomla-Tracks#55]
Hi julien,
i have a problem with the sort on frontend...
i have installed the newest 3.0.3 version tracks on my joomla 3.6.0

http://abload.de/image.php?img=tracks_2vmb0z.jpg:
this show you the install folder. i installed the modules, plugins and the marked file. without failure.

http://abload.de/image.php?img=tracks_5v6sya.jpg
here the install-info after install the yellow marked file ...

http://abload.de/image.php?img=tracks_1haa92.jpg:
i was surprised when i see the version number in joomla... i don´t see the 3.0.3 version???

http://abload.de/image.php?img=tracks_3krlt7.jpg:
at backend the date is sort correctly.

http://abload.de/image.php?img=tracks_43al4m.jpg:
display project summary with wrong sorted dates... ???
can i control the type to sort somewhere in the frontend?

need help. thanks
Frog

**Comment by julienV** [comment]
Hi Frog,

the ordering is set when you create the menu item:
![selection_008](https://cloud.githubusercontent.com/assets/169588/17618328/581a18da-607f-11e6-9518-ad787fcd509e.jpg)
it's based on season/competition/project ordering (not on the dates)

And I forgot to change the version number in the installer, that is why the info in backend is wrong...

**Comment by Frog65** [comment]
hi julien,
the problem is, i can´t find the layout(ordering) set when i create/edit the new/existing race-calendar.

i switched the language from german to english and find out that the translation is not clear.
now we talk about same program-key-words.

have please a look to the append picture who show my problem...
https://abload.de/img/tracks_sortcqs4m.jpg

2 differnt "projects" 
- racecalendar "MCC-GT3" is **not** ordering asc
- racecalendar "Procar-Masters" is ordering asc

do you have any idea???

thanks alot
Frog

**Comment by julienV** [comment]
did you order the projects in the backend ?
![tooltip_010](https://cloud.githubusercontent.com/assets/169588/17624354/8b9a9494-60a4-11e6-871b-a318dc950f84.jpg)

**Comment by Frog65** [comment]
i think i don´t order the 46 projects in our tracks ...
https://abload.de/img/tracks_sort_7c0j1o.jpg

**Comment by julienV** [comment]
Sorry, i meant you have to order the project rounds in backend
![selection_011](https://cloud.githubusercontent.com/assets/169588/17642229/bdeff3be-613d-11e6-8d88-2e639b40b572.jpg)

**Comment by Frog65** [comment]
hi julien,

i have ordered the project rounds asc... (see left pic)
but the view isn´t ordered right .. (see pic right)

<a href="http://abload.de/image.php?img=tracks_sort_8ymsya.jpg"><img src="https://abload.de/thumb/tracks_sort_8ymsya.jpg" /></a> <a href="http://abload.de/image.php?img=tracks_sort_94fsdk.jpg"><img src="https://abload.de/thumb/tracks_sort_94fsdk.jpg" /></a>

**Comment by julienV** [comment]
you need to click on the 'ordering' arrow i higlighted in the previous pick, and then drag and drop the rows... What you are showing me there is that you ordered by dates in the backend view, but it doesn't set anything.
it works exactly the same as ordering joomla categories

**Comment by Frog65** [comment]
ok.
i see in the backend project-round list that the ordering (by dates) is perfect. hmm i thought, why i had to do this manualy per drag and drop to the same position???

now i click first on the highlighted field and drag and drop the rows. down and up to the same position before. then i check the frontend and was surprised. the ordering are now correct.

thanks alot 
frog

**Comment by julienV** [comment]
because for some reason people might want an ordering in frontend that is not based on date... so there is a manual ordering for project rounds.
