### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by jbuddace** [julienV/Joomla-Tracks#57]
Hi, when i try to install Track i have this error: "Fatal error: Call to undefined method JComponentHelper::isInstalled() in /[...]/libraries/redcore/bootstrap.php on line 77"
what is?

**Comment by julienV** [comment]
Hi,

which version of joomla are you trying to install on ?

**Comment by jbuddace** [comment]
I tried with 3.2.3 and 3.6.2 versions. Same error.

**Comment by julienV** [comment]
could you try to install first latest version of redcore:
https://github.com/redCOMPONENT-COM/redCORE/releases/download/1.8.8/redCORE-v1.8.8.zip
