### ISSUE TITLE
comma not displayed

### ISSUE THREAD

**Issue by Frog65** [julienV/Joomla-Tracks#59]
hi julien

i have under COM_TRACKS_EVENTTYPES the COM_TRACKS_POINTS_COUNT on YES and the values are 3,2.25,2,1.75,1.5,1.25,1,0.75,0.5,0.25 entered.

The Qualysesson a driver has finished on Place 2 (2.25 points). 
The Sprintrace and the Mainrace the driver both on place 1 (2 * 20 points)
-> Points overall = 42,25. (displayed 42 !!)

The comma value is not completely visit on the module at position "contentright" and the summary-Table.

Have a look to the attached pictures.

Why the values not fully displayed? What can i do?

Thanks
Frog

https://abload.de/img/tracks_26tbj9.jpg
https://abload.de/img/tracks_14bym3.jpg
https://abload.de/img/tracks_3ydzu3.jpg

**Comment by julienV** [comment]
I fixed it for you in 3.0.5, which i just released.
You should see that the update is available in joomla backend, please let me know if not.

**Comment by Frog65** [comment]
i have check for update in joomla backend and updated it.
now the points are all right.
many thanks

**Comment by sudkarting** [comment]
Hello,
I installed version 3.0.5 but joomla tells me that I always version 3.0.4 (in the management of extensions) in addition it indicates to me that a version, the 3.0.5 is available ...
thanks

**Comment by julienV** [comment]
fixed... run the update again, should be ok now

**Comment by sudkarting** [comment]
Very Good!!! Thanks

i have an error with version 3.04 and 3.0.5, this message :
 "String could not be parsed as XML: com_j2xml/j2xml.php"

Regards

**Comment by julienV** [comment]
it has nothing to do with tracks...
      
      On 18/03/2017 17:34, sudkarting wrote:
    
    
      Very Good!!! Thanks
      i have an error with version 3.04 and 3.0.5, this message :
        "String could not be parsed as XML: com_j2xml/j2xml.php"
      Regards
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/julienV/Joomla-Tracks","title":"julienV/Joomla-Tracks","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/julienV/Joomla-Tracks"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sudkarting in #59: Very Good!!! Thanks\r\n\r\ni have an error with version 3.04 and 3.0.5, this message :\r\n \"String could not be parsed as XML: com_j2xml/j2xml.php\"\r\n\r\nRegards"}],"action":{"name":"View Issue","url":"https://github.com/julienV/Joomla-Tracks/issues/59#issuecomment-287557561"}}}
