### ISSUE TITLE
results in driver list - comma not displayed

### ISSUE THREAD

**Issue by Frog65** [julienV/Joomla-Tracks#60]
hi julien,
i think its a visible problem.

for qualy results i have com_tracks_eventtypes points with comma (eg. 3,2.25,2,1.75,1.5,1.25,1,0.75,0.5,0.25)
(its a another problem i have a few weeks before)

when i look at the race weekend list (qualy, sprint and mainrace) al values completey displayed:
Laguna seca: https://abload.de/img/tracks_101y0qet.jpg
monza: https://abload.de/img/tracks_1115jprx.jpg

when i click on a drivers name the comma-value is missing:
https://abload.de/img/tracks_121xto6q.jpg
(the 17.69 is right displayed. i think because the comma is coming from bonus-points. by qualy-results the comma comes from the eventtypes)

can you have a look of this display error. Thanks

frog

**Comment by julienV** [comment]
I fixed it and released 3.0.6. There are other improvements as well.
You should see the update available in joomla backend, or download it from my website.

**Comment by Frog65** [comment]
thanks julien for the fast fix !!!
now all right displayed :-)
