### ISSUE TITLE
error when use button "add all" in event results

### ISSUE THREAD

**Issue by agentemurphy** [julienV/Joomla-Tracks#61]
Hi,
when i use the button "add all" in event result print this error :(

Exception:Unknown column 'pi.number' in 'field list' SQL=INSERT INTO #__tracks_events_results (individual_id, team_id, event_id, `number`) SELECT pi.individual_id, pi.team_id, 49, `pi.number` FROM #__tracks_participants AS pi WHERE pi.project_id = 1
#0 /home/DB-NAME/public_html/libraries/redcore/database/driver/mysqli.php(71): JDatabaseDriverMysqli->execute()
#1 /home/DB-NAME/public_html/administrator/components/com_tracks/models/eventresults.php(325): RDatabaseDriverMysqli->execute()
#2 /home/DB-NAME/public_html/administrator/components/com_tracks/controllers/eventresults.php(31): TracksModelEventResults->addAll()
#3 /home/DB-NAME/public_html/libraries/legacy/controller/legacy.php(702): TracksControllerEventresults->addall()
#4 /home/DB-NAME/public_html/administrator/components/com_tracks/tracks.php(57): JControllerLegacy->execute('addall')
#5 /home/DB-NAME/public_html/libraries/cms/component/helper.php(405): require_once('/home/DB-NAME/...')
#6 /home/DB-NAME/public_html/libraries/cms/component/helper.php(380): JComponentHelper::executeComponent('/home/DB-NAME/...')
#7 /home/DB-NAME/public_html/libraries/cms/application/administrator.php(98): JComponentHelper::renderComponent('com_tracks')
#8 /home/DB-NAME/public_html/libraries/cms/application/administrator.php(152): JApplicationAdministrator->dispatch()
#9 /home/DB-NAME/public_html/libraries/cms/application/cms.php(261): JApplicationAdministrator->doExecute()
#10 /home/DB-NAME/public_html/administrator/index.php(51): JApplicationCms->execute()
#11 {main}

**Comment by julienV** [comment]
fixed, released 3.0.6.1

**Comment by agentemurphy** [comment]
More thax julien:)

Dario Lo Piccolo
Cell. 3282662374

7 apr 2017, 22:31 +0200, Julien Vonthron <notifications@github.com>, ha scritto:

**Comment by agentemurphy** [comment]
but i can't download the update :(

**Comment by julienV** [comment]
it works, it's just i forgot to update the version number in new version, but it's fixed now
