### ISSUE TITLE
no winner displayed in race overview

### ISSUE THREAD

**Issue by Frog65** [julienV/Joomla-Tracks#62]
hi julien,

i dont know why the winner-name aren´t displayed in the race/saison-overview (calendar).
i think it has work few days ago. (2 races we have until finished)
https://abload.de/img/tracks_winnern2swk.jpg

(version first 3.0.6 than update to 3.0.6.1, but no change)
do you have an idea? thanks

frog

**Comment by agentemurphy** [comment]
yes, don't work function "Enable stats"
    
    Il 09/04/2017 22:58, Frog ha scritto:
    
    
      hi julien,
      i dont know why the winner aren´t displayed in the
        race-overview (calendar).
        i think it has work few days ago.
        https://abload.de/img/tracks_winnern2swk.jpg
      do you have an idea? thanks
      frog
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/julienV/Joomla-Tracks","title":"julienV/Joomla-Tracks","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/julienV/Joomla-Tracks"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"no winner displayed in race overview (#62)"}],"action":{"name":"View Issue","url":"https://github.com/julienV/Joomla-Tracks/issues/62"}}}
    
    
   
	
      
		Mail priva di virus. www.avast.com

**Comment by julienV** [comment]
yes, you need to have 'enable stats' set to yes for your 'main' event type (e.g: race, not qualifying)

i guess, I should have set this by default to enabled, to prevent this upgrade issue.

![selection_048](https://cloud.githubusercontent.com/assets/169588/24882845/d078784a-1e42-11e7-80a3-a1205dfb23aa.jpg)

**Comment by agentemurphy** [comment]
i have this parameter in enabled but don't work it :(
    
    
    Il 10/04/2017 23:10, Julien Vonthron ha
      scritto:
    
    
      yes, you need to have 'enable stats' set to yes for your 'main'
        event type (e.g: race, not qualifying)
      i guess, I should have set this by default to enabled, to
        prevent this upgrade issue.
      
      —
        You are receiving this because you commented.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/julienV/Joomla-Tracks","title":"julienV/Joomla-Tracks","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/julienV/Joomla-Tracks"}},"updates":{"snippets":[{"icon":"PERSON","message":"@julienV in #62: yes, you need to have 'enable stats' set to yes for your 'main' event type (e.g: race, not qualifying)\r\n\r\ni guess, I should have set this by default to enabled, to prevent this upgrade issue.\r\n\r\n![selection_048](https://cloud.githubusercontent.com/assets/169588/24882845/d078784a-1e42-11e7-80a3-a1205dfb23aa.jpg)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/julienV/Joomla-Tracks/issues/62#issuecomment-293080016"}}}
    
    
   
	
      
		Mail priva di virus. www.avast.com

**Comment by julienV** [comment]
really ? if possible, please send me an access to jlv@jlv-solutions.com

**Comment by Frog65** [comment]
i have enabled this option and now the winner is visible!!!
thanks
