### ISSUE TITLE
no two winner if exist 2 race rounds

### ISSUE THREAD

**Issue by agentemurphy** [julienV/Joomla-Tracks#63]
This race has 2 rounds:
http://www.asfaltorovente.it/competizioni-campionati/campionato-ladder/risultati-gare/roundresult/37-stati-uniti-road-atlanta
But in the results there is only one winner:
http://www.asfaltorovente.it/competizioni-campionati/campionato-ladder/risultati-gare

**Comment by julienV** [comment]
yes, because here the global winner is displayed, according to the point earned in the round.
as Salvatore Gattuccio earned 75 + 50, he is the winner.
To display the winner of each 'subround' would need another way of computing 'winner' in that view. It's possible, but needs a plugin development.

**Comment by agentemurphy** [comment]
Ok thx Julien!

Dario Lo Piccolo

14 apr 2017, 10:57 +0200, Julien Vonthron <notifications@github.com>, ha scritto:
