### ISSUE TITLE
Event Results input box width + extra colums + more reuslts

### ISSUE THREAD

**Issue by smileysit** [julienV/Joomla-Tracks#65]
Hi
i need to change the input box width on the "Event results" page, 
What is the better way to adjust?

i added 3 more columns to the "Event results", Total Raced, Total Won and Total DNF (did not finish)
is it possible to auto calculate the percentage ?

Thanks
Chase

**Comment by julienV** [comment]
to change the size of the input ox, you can do either do it with css, or with a joomla css override.

for the 3 columns, this requires development.

**Comment by smileysit** [comment]
have added four extra column's for extra data, displays and save's ok

still stuck on the inputbox width for this page, have change in 4 or 5 locations, no luck
administrator/index.php?option=com_tracks&view=eventresults&event_id=
