### ISSUE TITLE
next update

### ISSUE THREAD

**Issue by smileysit** [julienV/Joomla-Tracks#66]
when can we expect the next update?

**Comment by smileysit** [comment]
great i see you back at work updating the plugin,  have several requests to suggest.

**Comment by smileysit** [comment]
Tracks Config > Default folder for teams pictures > (hover on title)  pop up window text

**Comment by smileysit** [comment]
Edit Project > Competition + Season > (hover on title) pop up window text
![Tracks edit project](https://user-images.githubusercontent.com/18531908/79802732-dd10e000-83a3-11ea-8367-187516291c3f.jpg)

**Comment by smileysit** [comment]
Edit individual, you have 'Country', it would also be good to have "State" as an option

**Comment by smileysit** [comment]
Edit team Edit, Team vehicle, it would be good to have 
"Team vehicle" = Picture +  Description + Link to their website (social link) 
plus another tab for
"Sponsor" = Picture +  Description + Link to their website (social link)

**Comment by smileysit** [comment]
Drag racing, currently Tracks has Top 3, Top 5 and Top 10.
It would be good to also support Top 2, Top 4 and Top 8.
- - - - - - -
It would be good to have 4 custom columns in results.
So we could add numbers (time or number of drivers qualified etc) or short text as custom reference.

**Comment by julienV** [comment]
ok, thanks for the feedback and request ;)

**Comment by julienV** [comment]
> Edit individual, you have 'Country', it would also be good to have "State" as an option

there is a state field already in the 'address' tab, is that not enough?

**Comment by julienV** [comment]
@smileysit i fixed the strings, and added a 'custom top' option, so you can create any top you want (because i am sure somebody else would have asked a 'top 11' and 'top 17' at some points.
and i added support for custom fields, but as a paid plugin (man gotta eat) ;)
