### ISSUE TITLE
Update From Joomla 2.5.28 to 3.8 (TRacks Version 2.5-1.0.8)

### ISSUE THREAD

**Issue by jeli1979** [julienV/Joomla-Tracks#67]
Hi Julien,
just a question. I have to migrate from Joomla 2.5.28 to Joomla 3.x now, because PHP 5.6 is not supported by my hoster anymore. My Tracks Version is 2.5-1.08.. 
What´s the upgrade path? Is it possible to migrate the component and the data to Tracks Version 3.08? Is there a documentation how to do this? 
Unfortunately the forum isn´t open anymore, also I have no access to the documentation. Thank you! 
Regards Jens

**Comment by julienV** [comment]
sorry, never answered, but the solution was to just update Tracks version...
