### ISSUE TITLE
Editar perfil....

### ISSUE THREAD

**Issue by monster3dani** [julienV/Joomla-Tracks#68]
Hola, te escribo en castellano mejor....
Uno de los problemas que me encuentro y que todos los usuarios no pueden hacer es editar su perfil
![image](https://user-images.githubusercontent.com/64259984/80207807-258ffe00-862f-11ea-9551-cff25eca5453.png)
Cuando edito el perfil y por ejemplo añado una imagen, al guardar no hay modificacion del perfil
![image](https://user-images.githubusercontent.com/64259984/80207918-6851d600-862f-11ea-8d5f-b7973d995611.png)

**Comment by julienV** [comment]
ok i'll check thanks

**Comment by julienV** [comment]
can you try with the attached version here?
[tracks-v3.0.11-13-gbce1378.zip](https://github.com/julienV/Joomla-Tracks/files/4539543/tracks-v3.0.11-13-gbce1378.zip)

**Comment by smileysit** [comment]
Date of birth, if a driver does not have a Date of birth when you edit the profile (either front end or backend) a "Date of birth" is auto inserted. There should also be a option to publish/hide the date of birth.

**Comment by smileysit** [comment]
I have tested the image fix, the images uploaded the the folder specified in the Tracks setting... This "_1588025024.jpg" was added to the original name.  So the edit is working.

**Comment by julienV** [comment]
the date of birth has a parameter to show/hide it in the version included above. I'll fix about it being auto filled...

**Comment by monster3dani** [comment]
Hola, pues yo tengo que tener mala suerte, no puedo subir imagenes, he probado la version adjunta julienV, ahora es peor, no me sale nada... pagina en blanco
![image](https://user-images.githubusercontent.com/64259984/80430784-f360f380-88ef-11ea-8446-6548b74af8f0.png)

**Comment by julienV** [comment]
try to enable debug, and set error reporting to maximum in your joomla configuration, and try again to see if you get errors

**Comment by monster3dani** [comment]
Nada, no veo errores, no soy muy profesional en esto, me limito subir modulos e instalar pocas cosas, siento no poder ayudarte, sigue sin salir el perfil del usuario...

**Comment by julienV** [comment]
strange... can you try this version then: 
[tracks-v3.0.11-15-gdbd41eb_no_redCORE.zip](https://github.com/julienV/Joomla-Tracks/files/4542603/tracks-v3.0.11-15-gdbd41eb_no_redCORE.zip)

**Comment by julienV** [comment]
oh, and you might need to recreate the 'profile' menu item, if you have one, because i changed the way it works...

**Comment by smileysit** [comment]
Request: have a menu open to display all winners from 1 event.
![Screenshot_4](https://user-images.githubusercontent.com/18531908/80441941-4918b880-894f-11ea-901f-d7d8124addba.jpg)

**Comment by monster3dani** [comment]
> extraño ... ¿puedes probar esta versión entonces:
> [tracks-v3.0.11-15-gdbd41eb_no_redCORE.zip](https://github.com/julienV/Joomla-Tracks/files/4542603/tracks-v3.0.11-15-gdbd41eb_no_redCORE.zip)

Gracias, vuelve a funcionar, pero el problema anterior sigue estando, no puedo modificar el perfil...

**Comment by julienV** [comment]
can you write me using jlv@jlv-solutions.com, maybe i'll need to debug from yoursite directly... because i don't have any other explanation at the moment

**Comment by julienV** [comment]
@monster3dani works now, it needed a 'individual list' menu item for the links to work properly with sef on.

@smileysit PLEASE create separated issues!!

**Comment by monster3dani** [comment]
WOWOWOW THANKS!!!!!!

**Comment by julienV** [comment]
> Request: have a menu option to display all winners from 1 event.
> ![Screenshot_4](https://user-images.githubusercontent.com/18531908/80441941-4918b880-894f-11ea-901f-d7d8124addba.jpg)

https://tracks.jlv-solutions.com/all-rounds/australian-grand-prix

**Comment by smileysit** [comment]
Yes, display all winners from 1 event... it look great. thankyou
