### ISSUE TITLE
Request - module - driver/team summary

### ISSUE THREAD

**Issue by julienV** [julienV/Joomla-Tracks#70]
from: https://tracks.jlv-solutions.com/forum/tracks-support/11-request-module-driver-team-summary#21
------------------------------------------
Hi!

Would be awesome if there is a module that's showing a drivers profile on a assigned user. For example my Joomla profile (Uncommonly) is assigned to a driver called ''Lewis Hamilton''. When I get loged in into the website, that module shows on a X place on the website showing my drivers name ( Lewis Hamilton ), overall points, podiums, completed races, etc, ete information about drivers carrer. If my Joomla profile is not assigned to a driver the module could return a blank info or a custom message.

Suggesting all of the above for team as well. :) ''Uncommonly'' is assigned to a team ''Mercedes''. When logged in, module shows on a X place on the website with usefull info and statistics about the team that Joomla profile is assigned to.

No matter free or paid, I think this is a ''MUST BE'' addition to the component! :)

**Comment by julienV** [comment]
This is what it looks like so far:
![Selection_669](https://user-images.githubusercontent.com/169588/81481244-d94bdd00-922e-11ea-8d5b-ec9d5a7ce8fa.png)

**Comment by julienV** [comment]
improved with picture (optional)
![Selection_671](https://user-images.githubusercontent.com/169588/81487538-71ad8600-925e-11ea-8b5c-d6d87ea5aab1.png)

**Comment by monster3dani** [comment]
WOW this is getting better by the minute

**Comment by julienV** [comment]
I generalize the module, so now you can either link it to the current logged in user (your request), or display a random user, or a selected user.
it's set on 'random' mode on the demo page: https://tracks.jlv-solutions.com/tracks-demo

**Comment by julienV** [comment]
added team module on tracks demo page

**Comment by julienV** [comment]
HI, it's here: https://jlv-solutions.com/products/tracks/individual-and-team-modules
but don't forget to update tracks to 3.0.13 too
