### ISSUE TITLE
Future Races Module

### ISSUE THREAD

**Issue by amirandap** [julienV/Joomla-Tracks#71]
It would be really nice addition a module that would list the future races, maybe filtered by project, or including all projects.

[https://imgur.com/L1vHaln](url)

**Comment by julienV** [comment]
@amirandap see https://tracks.jlv-solutions.com/tracks-demo

**Comment by smileysit** [comment]
yeah, i do like that, great job.

**Comment by julienV** [comment]
implemented and available
