### ISSUE TITLE
Request: No and Ranks added to more result tables.

### ISSUE THREAD

**Issue by smileysit** [julienV/Joomla-Tracks#72]
Hi
can we add the Number (No) and Rank to other Tables also?
some driver change their No (and vehicle) during the season. 
some driver's overall No (as in their personal ranking for the season) changes during the year.
while rank relates to that particular race.
![no 1](https://user-images.githubusercontent.com/18531908/81618602-0b299300-942b-11ea-9f9f-751dae5cfc84.jpg)

**Comment by julienV** [comment]
I see your point about adding the number, but adding the rank would be confusing imo

**Comment by smileysit** [comment]
I am using the Drivers Number (No) as a overall yearly ranking, and i am using the Drivers Rank as their rank for a race (race series), hence why i requested displaying the extra data. There would be a setting to publish or unpublish those columns similar to the other settings. :)

**Comment by julienV** [comment]
ok for the number in individual results i guess, but the rank is already there in the course result, it's the "pos" column...

**Comment by smileysit** [comment]
Thank you

**Comment by julienV** [comment]
i added the option for number in results history
