### ISSUE TITLE
ERROR: 1064 New Upcoming Module Results

### ISSUE THREAD

**Issue by amirandap** [julienV/Joomla-Tracks#74]
Im getting the following error with the new upcoming module result

ERROR: 1064
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') GROUP BY e.id ORDER BY CASE WHEN e.start_date > 0 THEN e.start_DATE ELSE pr...' at line 5

www.f1esportsrd.com

**Comment by julienV** [comment]
fixed
