### ISSUE TITLE
[bug] Cannot change Project Round status

### ISSUE THREAD

**Issue by kosin-ski** [julienV/Joomla-Tracks#81]
Hi @julienV 👋
I found a small bug in **Project rounds** view. In the table with rounds, there is a **Status** column. Every round has a button to change Status from Published to Unpublished and vice versa. Unfortunately, this doesn't work. When you click it an error appears: **Unknown column 'state' in 'field list'**. Screenshot attached. This not a dealbreaker but would be great to have it working :)
<img width="921" alt="Zrzut ekranu 2021-06-21 o 22 26 53" src="https://user-images.githubusercontent.com/83312926/122823975-4d84fb00-d2e0-11eb-9aa8-a277883ba5e7.png">

**Comment by julienV** [comment]
thanks, good catch, fixing it
