### ISSUE TITLE
Importing my own results

### ISSUE THREAD

**Issue by kosin-ski** [julienV/Joomla-Tracks#82]
Hi @julienV 👋
There is an import plugin in Tracks that can get F1 results imported. But is there any way to import my own results? Would be great to have that possibility to import a file (xml for example) with correctly formatted data to be put into Tracks.
Thanks!

**Comment by julienV** [comment]
Hi,
indeed maybe i could have some xml importer...
i'll think about it ;)

**Comment by greg-digit** [comment]
Importing, I have successfully imported 120+ events and results from a csv file/s and phpmyadmin directly into the tables. All about getting your data structure sorted out first.
