### ISSUE TITLE
Joomla 3.10 Upgrade

### ISSUE THREAD

**Issue by fatboybrit** [julienV/Joomla-Tracks#84]
![error](https://user-images.githubusercontent.com/74975436/131152583-0a93e584-4baa-48b9-a237-d8e5784fc5da.PNG)
Firstly thanks for a great extension. It's worked pretty much flawlessly for me since first use over a year ago.....

.... until now. I am trying to get my head round what is going on.

I upgraded to Joomla 3.10.1. PHP has been at 7.4.21 for quite a while now. Tracks 3.0.18.1

Now when I try to add a new project round or an event into a round I get "0 Call to a member function createModel() on null" I have researched this general issue and most have been fixed by disabling the Quick Check PHP Version Plugin.

Here is the thing, this is only happening to me with Tracks. - I have upgraded to 3.0.19.1 but no difference. I suspect this maybe at PHP/Joomla level. But wondered if anyone has come across this, or you can point me in the right direction. Thanks - P
![error 1](https://user-images.githubusercontent.com/74975436/131152632-27147c21-5fcc-4187-8dee-174125b718be.PNG)
![error](https://user-images.githubusercontent.com/74975436/131152649-8abb5f37-fd9a-4941-afa6-c91297f508bc.PNG)

**Comment by fatboybrit** [comment]
As a footnote, this only seems to occur when I am trying to create a record, not when I am modifying a record.

**Comment by julienV** [comment]
Hi, thanks for reporting. 
It's a bug in redCORE, i released a workaround version 3.0.19.2, it should appear in your ipdate soon, or you can get it from the website.
let me know if it's ok then!

**Comment by fatboybrit** [comment]
Thanks JV, appreciate the quick response, fantastic. If its any consolation, I think a few extensions may have been caught out by the latest Joomla release using later PHP versions, Seems also if an extension uses Akeeba old FOF there is a similar bug. Thanks once again for the support, and a great extension/ - P

**Comment by fatboybrit** [comment]
Just installed upgrade 3.0.19.2 and looks good. ! Brilliant !. Thanks - P
