### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by austin2626** [julienV/Joomla-Tracks#87]
Hi, when I start install process, I have everytime error. Please can anyone help me with this problem??
![Bez názvu](https://user-images.githubusercontent.com/91564627/135146503-9621a4be-37a3-4f1b-becc-f5a11e98eb10.png)
.

**Comment by julienV** [comment]
you just need to upgrade to latest

**Comment by austin2626** [comment]
I have latest version.. This error on latest version, other versions same problem.

**Comment by julienV** [comment]
what's your version of joomla? and which install file are you using? something might be conflicting,

**Comment by austin2626** [comment]
Joomla! 3.10.2 and I use tracks-v3.0.19.2.zip.

**Comment by austin2626** [comment]
probably problem in redCORE. I try install redCORE 2.2.0 and I try other versions but i have problem in installation (Specified key was too long; max key length is 1000 bytes)

**Comment by austin2626** [comment]
Okey nevermind but thank you for your time. I was unlucky :D
