### ISSUE TITLE
Install issue ?

### ISSUE THREAD

**Issue by fatboybrit** [julienV/Joomla-Tracks#90]
Hi Julien, ...19.2 working still flawlessly for me on the primary sit. Thanks for the last bug fix. Starting up a new site for another sister site and I am getting install issues. I don't know whether its MySQL or Tracks. I can install other modules fine. The install halts and I get no component folders installed. REDCORE (I think) is going in OK but Tracks is registered in the module table in SQL but thats it. A couple of  screenshots for you if this helps.
![tracks_bug](https://user-images.githubusercontent.com/74975436/155840376-09661750-36a4-4522-958d-4595212b20eb.PNG)
![tracks_bug2](https://user-images.githubusercontent.com/74975436/155840435-211580a9-2e0f-468b-929d-4288e8ba7512.PNG)

Keep going ! This is a great extension !

Thanks - Phil

**Comment by julienV** [comment]
thanks for reporting, i just published 3.0.19.3 to fix it.
let me know if it's ok now.

**Comment by fatboybrit** [comment]
Brilliant ! thanks Julien. It's a brilliant extension. I love it ! Thanks for your continuing support. - Phil
________________________________
